### ISSUE TITLE
Unreachability test bug?

### ISSUE THREAD

**Issue by genesith** [cohere-ai/magikarp#13]
Hello, big fan of this work!

I asked previously on Twitter about testing for unreachable tokens, since it is very tricky.
I gave the implementation here a try on Llama3 and I'm getting incorrect classifications.
Some of these tokens are reachable, even if the self-reencoding method fails.

```
{'i': 80521, 'raw_vocab': 'Ġ?><?', 'category': 'UNREACHABLE_MULTI_TOKEN', 'decoded': '?><?', 'reencoded_ids': [4887, 1340], 'reencoded': ['?>', '<?']}
>>> ll3.clean_encode(ll3.clean_decode(80521)) # Self decode/encode fails
[4887, 1340]
>>> ll3.clean_encode(" "+ll3.clean_decode(80521)) # But it's reachable
[80521]
```
I'm wondering if this is due to either 1) this is an edge case where the clean_encode/clean_decode check fails or 2) I'm running something incorrectly (e.g. library versions change results).

I wanted to do a quick sanity check to see if its 2), but the results in the repo dont label which tokens were unreachable.
It would be very helpful if you could confirm if its 1) or 2).

**Comment by sanderland** [comment]
I think any unreachable tokens for Llama3 disappeared after the 0.19.0 -> 0.19.1 breaking change in tokenizers which fixed tokens bypassing merge rules

https://raw.githubusercontent.com/cohere-ai/magikarp/main/results/reports/meta_llama_Meta_Llama_3_8B.md

**Comment by sanderland** [comment]
It's definitely not perfect either though, in DeepSeek v1 I've found an edge case in which the pretokenizer splits a single token's vocab 🫠

**Comment by genesith** [comment]
Oh I see, there's no unreachable tokens in the report because all were reachable.
Hmm... then the code must be running incorrectly for me. I'll try to figure it out.
(On transformers 4.41.1 and tokenizers 0.19.1)

**Comment by genesith** [comment]
Okay the issue was that I was trying to pass my own tokenizers instances to the TokenizerAnalyzer, but this meant the default clean_up_tokenization_spaces=True was messing with decoding.

Relying on the default loading in the __init__ function fixed this. Totally my own issue.

```
self.tokenizer = tokenizer or AutoTokenizer.from_pretrained(
            model_id,
            use_fast=use_fast,
            clean_up_tokenization_spaces=False,
            trust_remote_code=trust_remote_code,
        )
```


There's definitely many ill-configured tokenizers out there. I think the main cause is that the process of converting custom vocabs to work correctly with the bpe-merges is still poorly documented. Might not be a big deal but might also spawn some Karps.
